import os
import cv2
import glob
from ultralytics import YOLO, YOLOWorld
import supervision as sv

def offline_auto_annotate(raw_folder_path):
    print("Loading YOLO-best.pt for offline annotation...")
    
    # Update this path if your model file is in a different folder
    current_dir = os.path.dirname(os.path.abspath(__file__))
    model_path = os.path.join(current_dir, 'runs/detect/train-3/weights/best.pt')

    model = YOLO(model_path)
    
    # Grab all JPG images in the raw folder
    image_paths = glob.glob(os.path.join(raw_folder_path, "*.jpg"))
    total_images = len(image_paths)
    
    if total_images == 0:
        print(f"No images found in {raw_folder_path}. Please check the folder path.")
        return
        
    print(f"Found {total_images} raw images. Starting auto-annotation...")
    
    annotated_count = 0
    
    for img_path in image_paths:
        color_image = cv2.imread(img_path)
        if color_image is None:
            continue
            
        height, width = color_image.shape[:2]
        
        # --- Apply the CLAHE lighting fix in memory ---
        # This helps the AI see the drone, but leaves your raw JPG file completely untouched
        lab = cv2.cvtColor(color_image, cv2.COLOR_BGR2LAB)
        l_channel, a, b = cv2.split(lab)
        clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
        cl = clahe.apply(l_channel)
        enhanced_lab = cv2.merge((cl, a, b))
        processed_image = cv2.cvtColor(enhanced_lab, cv2.COLOR_LAB2BGR)
        
        # --- Run AI Detection ---
        results = model.predict(processed_image, device='cuda', conf=0.10, verbose=False)
        detections = sv.Detections.from_ultralytics(results[0])
        
        # NMS Filter to eradicate overlapping boxes
        detections = detections.with_nms(threshold=0.4)
        
        # --- Save the Label ---
        if len(detections.xyxy) > 0:
            # Grab the box with the highest confidence
            best_idx = detections.confidence.argmax()
            x1, y1, x2, y2 = detections.xyxy[best_idx]
            
            # Convert to YOLO normalized format (decimals between 0.0 and 1.0)
            x_center = ((x1 + x2) / 2) / width
            y_center = ((y1 + y2) / 2) / height
            box_w = (x2 - x1) / width
            box_h = (y2 - y1) / height
            
            # Save the .txt file directly next to the image with the same name
            base_filename = os.path.basename(img_path)
            txt_filename = os.path.splitext(base_filename)[0] + ".txt"
            lbl_path = os.path.join(raw_folder_path, txt_filename)
            
            with open(lbl_path, "w") as f:
                f.write(f"0 {x_center:.6f} {y_center:.6f} {box_w:.6f} {box_h:.6f}\n")
                
            annotated_count += 1
            
    print(f"\nDone! Successfully auto-annotated {annotated_count} out of {total_images} images.")
    print("Your dataset is ready to be dragged and dropped into Roboflow.")

if __name__ == "__main__":
    # Change this to the exact folder name generated by your raw capture script
    TARGET_FOLDER = "dataset_raw_negative_positive" 
    offline_auto_annotate(TARGET_FOLDER)
